export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT_BY_ID = "FETCH_PRODUCT_BY_ID";
export const ADD_TO_CART = "ADD_TO_CART";
export const LOAD_MORE = "LOAD_MORE";
export const CHANGE_CART_COUNTS = "CHANGE_CART_COUNTS";
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";
